services:
  car-cost-tracker-api:
    image: lgdweb/car-cost-tracker-api:latest
    container_name: car-cost-tracker-api
    environment:
      TZ: Europe/Paris
      DATABASE_URL: ${DATABASE_URL}
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: ${BETTER_AUTH_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      RUN_MIGRATIONS: 'true'
    volumes:
      - data:/data
    networks:
      - reverse-proxy-nw
      - default-nw
    restart: unless-stopped

  car-cost-tracker-web:
    image: lgdweb/car-cost-tracker-web:latest
    container_name: car-cost-tracker-web
    environment:
      TZ: Europe/Paris
      API_URL: ${API_URL}
      PUBLIC_API_URL: ${PUBLIC_API_URL}
    networks:
      - reverse-proxy-nw
      - default-nw
    restart: unless-stopped
    depends_on:
      - car-cost-tracker-api

volumes:
  data:

networks:
  default-nw:
    external: true
  reverse-proxy-nw:
    external: true
